version: "3"
services:  
  msclient:
    build: .\ms-client
    container_name: "msclient-dockercompose"
    ports:
      - 8080:8080
    depends_on:
      - mongodb  

  mongodb:
    image: mongo:latest
    container_name: mongodb-dockercompose
    ports:
      - 27017:27017      
